### ISSUE TITLE
Does not build on python 3.12

### ISSUE THREAD

**Issue by veenstrajelmer** [python-cachier/cachier#129]
`cachier` cannot be installed on Python 3.12 because of a `pathtools` dependency, which in turn depends on `imp`. The pathtools issue is https://github.com/gorakhargosh/pathtools.

`pathtools` is not imported in `cachier`, but it is stated as a requirement in the pyproject.toml:
https://github.com/python-cachier/cachier/blob/f1a96b8fec6b62d741181d8771890f4222c6a821/setup.py#L53-L57
It states that it is for `watchdog`, but if I look in that repos `pathtools` does not seem to be a requirement there.

Could this requirement not be removed so `cachier` is installable on Python 3.12?

**Comment by shaypal5** [comment]
I removed the `pathtools` dependency and things seem to work, by Python 3.12 testing doesn't work because of a pip issue. See here:
https://github.com/python-cachier/cachier/actions/runs/7186576860

**Comment by veenstrajelmer** [comment]
The action run you are pointing to states "this is likely not a problem with pip", so could it be that it is not a pip issue? If I scroll up a bit I see see `"AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?"`. This comes not from the code, but the [versioneer script](https://github.com/python-cachier/cachier/blob/d76e166ec047f87139391ee73dcbce372cbece2c/versioneer.py#L413). Reading in [the configparser documentation](https://github.com/jaraco/configparser/blob/17432aa1a99f16888ec76633597870cbd33cd3d9/README.rst?plain=1#L78) it seems that they have deprecated `SafeConfigParser` in favor of `Configparser`. It does not explain why this only occurs on py312 though, but it might help?

**Comment by shaypal5** [comment]
Oh snap! I misread that!

OK. So it does look like it's a versioneer issue!
I'm going to try to solution applied here:
https://github.com/Matoking/python-ed25519-blake2b/pull/3/files

**Comment by shaypal5** [comment]
Done. Released in `v2.2.2`

**Comment by veenstrajelmer** [comment]
Thanks a lot for these quick actions!
